package com.badwolfmc.guardian.core;

public enum DecisionReason {
    BEDROCK_POLICY,
    VANILLA_POLICY,
    OPTIFINE_POLICY,
    UNKNOWN_BRAND_POLICY,
    CLIENT_POLICY_ALLOWED,
    CLIENT_POLICY_BYPASSED,
    MOD_POLICY_BYPASSED,
    CERBERUS_VERIFIED,
    PROXY_ADMISSION_VERIFIED,
    PROXY_ASSERTION_REQUIRED,
    PROXY_ASSERTION_INVALID,
    CERBERUS_REQUIRED,
    CERBERUS_TIMEOUT,
    CERBERUS_PROTOCOL_UNSUPPORTED,
    MANIFEST_DENIED,
    MANIFEST_INVALID,
    CLIENT_DENIED,
    CONFIGURATION_ERROR
}
