plugins {
    id 'java-library'
}

dependencies {
    implementation project(':guardian-core')
    implementation project(':guardian-protocol')
    implementation project(':guardian-protection')
    compileOnly "io.papermc.paper:paper-api:${paper_api_version}"
    compileOnly "org.geysermc.floodgate:api:${floodgate_api_version}"
    compileOnly "net.luckperms:api:${luckperms_api_version}"

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "io.papermc.paper:paper-api:${paper_api_version}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

base {
    archivesName = 'guardian-paper'
}

tasks.named('jar') {
    from { configurations.runtimeClasspath.findAll { it.name.startsWith('snakeyaml-engine-') }.collect { zipTree(it) } }
    dependsOn project(':guardian-core').tasks.named('classes')
    dependsOn project(':guardian-protocol').tasks.named('classes')
    dependsOn project(':guardian-protection').tasks.named('classes')
    from(project(':guardian-core').sourceSets.main.output)
    from(project(':guardian-protocol').sourceSets.main.output)
    from(project(':guardian-protection').sourceSets.main.output)
}

def guardianVersion = version.toString()

processResources {
    inputs.property 'version', guardianVersion
    filesMatching('plugin.yml') {
        expand version: guardianVersion
    }
}

sourceSets {
    main.resources.srcDir rootProject.file('shared-resources')
}
